### ISSUE TITLE
node-gyp

### ISSUE THREAD

**Issue by yocontra** [nguyer/node-kinect#1]
Is there any chance you can switch to node-gyp? This isn't building on OSX and eventually I'd like to get it on an embedded device

**Comment by pgte** [comment]
It builds fine on my OSX.
What's the problem you're experiencing?

(Also, this module is still experimental, will be developing it during these following days.)

**Comment by yocontra** [comment]
I'm experiencing https://github.com/joyent/node/issues/3633

**Comment by pgte** [comment]
Fixed in 6ee39be638b74598046c8918e2d475721d611bd8
