### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by xhava** [nguyer/node-kinect#5]
with this i can send data to the arduino , u know if node-kinect can be used with johnny-five

**Comment by yocontra** [comment]
It depends on how you want to use it I guess. "Can I use X with Y" is a very broad statement and doesn't actually help us answer your question. Specifically what are you trying to do? You can't plug a kinect camera into an arduino so I'm assuming you have a Kinect and an Arduino plugged into your computer. Yes, you can do that. You can take data from the kinect and then do something with johnny-five and you shouldn't have problems.
