### ISSUE TITLE
motor control

### ISSUE THREAD

**Issue by timdream** [nguyer/node-kinect#7]
Hi, I wonder how hard it is to add motor control to the library? I have practically no C++ experience, but if that's something possible with copy-paste code and some speed reading of language reference, I am happy to try.

Or, please share if there is alternative out there (for controlling kinect w/ JavaScript).

**Comment by timdream** [comment]
https://github.com/timdream/node-kinect/compare?w=1

This is probably the simplest approach.

**Comment by pgte** [comment]
looks good to me.
are you sibmitting a PR?

**Comment by timdream** [comment]
Will do!
