### ISSUE TITLE
No depth or video data callbacks, all other functions working fine

### ISSUE THREAD

**Issue by flimshaw** [nguyer/node-kinect#9]
Was going nuts trying to get a socket server implementation working in Python for the kinect, so I decided to give your library a try.  It seems like everything's wired up correctly and most tests pass (LED controls, tilt etc) but I can't receive any video or depth info.  No error messages, it just times out after sending various write_register messages.

Kinect depth and video work fine in other apps so I'm pretty sure it's not a hardware issue.  Here's the test ouput: 

  1) Depth should allow to pass in a depth callback:
     Error: timeout of 60000ms exceeded
      at null.<anonymous> (/Users/charlie/code/kinect/node-kinect/node_modules/mocha/lib/runnable.js:156:19)
      at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

  2) Video should allow to pass in a depth callback:
     Error: timeout of 60000ms exceeded
      at null.<anonymous> (/Users/charlie/code/kinect/node-kinect/node_modules/mocha/lib/runnable.js:156:19)
      at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

And here's my npm list output:

kinect@0.2.0 ~/code/kinect/node-kinect
└─┬ mocha@1.21.1
  ├── commander@2.0.0
  ├─┬ debug@1.0.4
  │ └── ms@0.6.2
  ├── diff@1.0.7
  ├─┬ glob@3.2.3
  │ ├── graceful-fs@2.0.3
  │ ├── inherits@2.0.1
  │ └─┬ minimatch@0.2.14
  │   ├── lru-cache@2.5.0
  │   └── sigmund@1.0.0
  ├── growl@1.8.1
  ├─┬ jade@0.26.3
  │ ├── commander@0.6.1
  │ └── mkdirp@0.3.0
  └── mkdirp@0.3.5

Aaaand lastly:

libusb: stable 1.0.19
libfreenect: stable 0.4.3

Let me know if there is any more info that would help!

**Comment by BadBauds** [comment]
Any news concerning this issue?

In my case the test works perfectly but I can't get my program to run the callback (but I can control the led). I'm using an ARM machine (ODROID U3) with lubuntu 14.04.

I've tried with the same code on another computer (x86, Ubuntu 14.04) and it worked perfectly. Maybe it has to do with the ARM. But still, it is weird because the test works as normal (24 passing).

This issue is quite annoying because otherwise I really like the module and I also need it.

**Comment by nguyer** [comment]
Hi @flimshaw. I am the new maintainer of this repo now, and I'm looking through the open issues. Is this still an issue for you with the latest version?

**Comment by farazfazli** [comment]
@nguyer I am also facing the same issue, is this normal?
